#!/bin/bash

systemctl stop paddock_manager.timer
systemctl disable paddock_manager.timer
systemctl stop paddock_manager.service
systemctl disable paddock_manager.service
systemctl stop paddock_watcher.service
systemctl disable paddock_watcher.service
