name: publish-runner-x64

run-name: Publish x64 runner - ${{ github.sha }}
on:
  push:
    paths:
      - "runner/**"
      - ".github/workflows/publish-runner-x64.yml"
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: johannesrehrl/github-runners

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout runner only
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./runner/
          file: ./runner/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: ARCHITECTURE=x64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-x64
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:x64