name: publish-paddock-debian

run-name: Publish Paddock Debian package - ${{ github.sha }}
on:
  push:
    paths:
      - "paddock/src/**"
      - "paddock/installers/deb/**"
      - ".github/workflows/publish-paddock-debian.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Copy src into package structure
        run: |
          mkdir -p paddock/installers/deb/usr/lib/paddock
          cp -r paddock/src/. paddock/installers/deb/usr/lib/paddock

      - name: Set permissions on scripts
        run: |
          chmod 755 paddock/installers/deb/DEBIAN/postinst
          chmod 755 paddock/installers/deb/DEBIAN/prerm
          
      - name: Build .deb package
        run: |
          dpkg-deb --build paddock/installers/deb
          mv paddock/installers/deb.deb paddock-arm64.deb

      - name: Push to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: push
          format: deb
          owner: paddock
          repo: paddock
          distro: debian
          release: any-version
          file: paddock-arm64.deb